spring:
  application:
    name: arukas
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.h2/arukas
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 80
